/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.unknownrori.management.password.uas3.amikom;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.*;
import java.util.Base64;
import java.util.NoSuchElementException;
import java.util.Optional;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author UnknownRori
 */
public class MasterPasswords extends javax.swing.JFrame {

    private Koneksi koneksi;
    public static Optional<Connection> connection = Optional.empty();
    public static PasswordRepository repository = new PasswordRepository();
    public static Random random;
    public static Optional<FormPassword> formPassword;

    private String username = "root"; // INFO : EDIT THIS
    private String password = ""; // INFO : EDIT THIS
    private String db = "your_db"; // INFO : EDIT THIS
    private String host = "localhost:3306";

    /**
     * Creates new form MenuUtama
     */
    public MasterPasswords() {
        initComponents();
        this.random = new Random(System.currentTimeMillis());

        try {
            this.koneksi = new Koneksi(host, db, username, password);
            this.connection = this.koneksi.connect();
            if (this.connection.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Koneksi Gagal!");
            } else {
                JOptionPane.showMessageDialog(null, "Koneksi Berhasil!");
            }
        } catch (ClassNotFoundException err) {
            JOptionPane.showMessageDialog(null, "Mysql Driver gagal di load!");
        }

        this.refreshTable();
    }

    public void refreshTableModel() {
        DefaultTableModel TampilTabel = new DefaultTableModel();
        TampilTabel.addColumn("Nama");
        TampilTabel.addColumn("Payload");
        TampilTabel.addColumn("Password");

        repository.passwords.forEach((p) -> {
            TampilTabel.addRow(new Object[]{
                p.name,
                Base64.getEncoder().encodeToString(p.payload),
                p.password.orElse("************"),});
        });

        table1.setModel(TampilTabel);
    }

    public void refreshTable() {
        try {
            repository.all(MasterPasswords.connection.get());
            refreshTableModel();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Gagal mengambil data!");
        } catch (NoSuchElementException ex) {
            JOptionPane.showMessageDialog(null, "Koneksi Mysql tidak ada!");
        } catch (Exception e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(null, "Terjadi kesalahan!");
        }
    }
    
    private String getNameFromTable() {
        int row = table1.getSelectedRow();
        int col = 0;
        return table1.getModel().getValueAt(row, col).toString();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        cmdTambah = new javax.swing.JButton();
        cmdEdit = new javax.swing.JButton();
        cmdHapus = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cmdBuka = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama", "Payload", "Password"
            }
        ));
        jScrollPane1.setViewportView(table1);

        cmdTambah.setText("Tambah");
        cmdTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdTambahActionPerformed(evt);
            }
        });

        cmdEdit.setText("Edit");
        cmdEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdEditActionPerformed(evt);
            }
        });

        cmdHapus.setText("Hapus");
        cmdHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdHapusActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Manajemen Passwords");

        cmdBuka.setText("Buka");
        cmdBuka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBukaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmdBuka)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdHapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdTambah))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 907, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdTambah)
                    .addComponent(cmdEdit)
                    .addComponent(cmdHapus)
                    .addComponent(cmdBuka))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdTambahActionPerformed
        this.formPassword = Optional.of(new FormPassword());
        this.formPassword.get().setVisible(true);
        this.formPassword.get().addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                refreshTable();
            }
        });
    }//GEN-LAST:event_cmdTambahActionPerformed

    private void cmdBukaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBukaActionPerformed
        String val = getNameFromTable();
        String master = JOptionPane.showInputDialog("Masukan Master Password");

        try {
            MasterPasswords.repository.decrypt(MasterPasswords.connection.get(), val, master);
            refreshTableModel();
        } catch (NoSuchElementException ex) {
            System.out.println(ex);
            JOptionPane.showMessageDialog(null, "Koneksi Mysql tidak ada!");
        } catch (Exception e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(null, "Terjadi kesalahan!");
        }
    }//GEN-LAST:event_cmdBukaActionPerformed

    private void cmdHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdHapusActionPerformed
        String val = getNameFromTable();
        try {
            MasterPasswords.repository.delete(MasterPasswords.connection.get(), val);
            refreshTable();
        } catch (Exception e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(null, "Koneksi Mysql tidak ada!");
        }
    }//GEN-LAST:event_cmdHapusActionPerformed

    private void cmdEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdEditActionPerformed
        String val = getNameFromTable();
        this.formPassword = Optional.of(new FormPassword());
        this.formPassword.get().edit = true;
        this.formPassword.get().setNamaInput(val);
        this.formPassword.get().setVisible(true);
        this.formPassword.get().addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                refreshTable();
            }
        });
    }//GEN-LAST:event_cmdEditActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MasterPasswords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MasterPasswords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MasterPasswords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MasterPasswords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MasterPasswords().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdBuka;
    private javax.swing.JButton cmdEdit;
    private javax.swing.JButton cmdHapus;
    private javax.swing.JButton cmdTambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table1;
    // End of variables declaration//GEN-END:variables
}
